# .github/workflows/pr-checks.yml
name: Build, Test & Deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch: # ← Botão manual!
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rodar suíte de testes
        run: |
          docker compose -f docker-compose.test.yml up \
          --abort-on-container-exit --exit-code-from app
      - name: Limpar containers
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
