# .github/workflows/pr-checks.yml
name: Build, Test & Deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch:  # ← Botão manual!

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build imagem de teste
        run: docker build --target test -t app:test .
      
      - name: Rodar testes
        run: docker run --rm -e APP_KEY="base64:$(openssl rand -base64 32)" app:test php artisan test

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      APP_ENV: production

    steps:
      - uses: actions/checkout@v4
      
      - name: Login no registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
      
      - name: Gerar versão
        id: version
        run: echo "tag=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      
      - name: Buildar e taguear com a versão gerada
        run: docker build -t ghcr.io/juliobarros123/meu-projeto-laravel:${{ steps.version.outputs.tag }} .
        #         ↑ Use SEU usuário!
      
      - name: Publicar imagem no registry
        run: docker push ghcr.io/juliobarros123/meu-projeto-laravel:${{ steps.version.outputs.tag }}